version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:80"
    restart: unless-stopped
    networks:
      - common_network
networks: 
  common_network:
